1.18 server only mode
AlmostReliable/almostunified pull request #11
Opened 2022-09-27 14:56 UTC by LLytho

2022-09-27 15:11 UTC, DAmNRelentless requested changes

2022-09-27 15:11 UTC, DAmNRelentless commented on Common/src/main/java/com/almostreliable/unified/AlmostUnified.java
> +        return startupConfig;
I'd move the `initStartupConfig` functionality into this accessor in case it's still `null`.

2022-09-27 15:11 UTC, DAmNRelentless commented on Common/src/main/java/com/almostreliable/unified/AlmostUnified.java
> +    private static StartupConfig startupConfig;
annotate this as nullable

2022-09-27 15:26 UTC, DAmNRelentless approved these changes

2022-09-27 15:26 UTC, merged

2024-02-03 21:36 UTC, adamk33n3r commented
Is there any benefit to not running it server only?

2024-02-04 08:57 UTC, rlnt commented
> Is there any benefit to not running it server only?

Yes. On the client, we have JEI and REI integration. Almost Unified will hide unified items and only leave the preferred ones in the list. It also removes items from the tag lookup in recipes.